"""
Create the observation CSV for the original Foster (2019) model.

The original model excludes ALL Kaiser Q3 stations. This script filters
the modified_foster_2019 observations by removing Q3 broadband stations
(those with 3-character station names that the modified version retained).

Can be run from the refactored environment:
    mamba activate vs30_venv
    python dev/observations/foster_2019/create_foster_2019_observations.py

Alternatively, can be run from the legacy environment to generate from
raw sources (see create_modified_foster_2019_observations.py for details).
"""

from pathlib import Path

import pandas as pd

REPO_ROOT = Path(__file__).parent.parent.parent.parent
OBSERVATIONS_DIR = REPO_ROOT / "vs30" / "resources" / "observations"

INPUT_CSV = OBSERVATIONS_DIR / "modified_foster_2019_measured_vs30_independent_observations.csv"
OUTPUT_CSV = OBSERVATIONS_DIR / "foster_2019_measured_vs30_independent_observations.csv"


def main():
    print("Creating Foster (2019) observation CSV from modified version")
    print("=" * 70)

    df = pd.read_csv(INPUT_CSV, comment="#")
    print(f"Loaded {len(df)} observations from modified_foster_2019 CSV")

    # The modified version retains Kaiser Q3 stations with 3-character names.
    # The original excludes ALL Q3 stations. Drop the additionally retained ones.
    q3_broadband_mask = (
        (df["source"] == "kaiseretal")
        & (df["q"] == 3.0)
        & (df["station"].str.len() == 3)
    )
    n_dropped = q3_broadband_mask.sum()
    print(f"Dropping {n_dropped} Q3 broadband stations (3-char station names)")

    filtered = df[~q3_broadband_mask].copy()
    print(f"Remaining: {len(filtered)} observations")

    # Write with comment header for provenance
    with open(OUTPUT_CSV, "w") as f:
        f.write("# Foster (2019) independent observations\n")
        f.write("# Generated by: dev/observations/foster_2019/create_foster_2019_observations.py\n")
        f.write(f"# Source: {INPUT_CSV.name} ({len(df)} rows)\n")
        f.write(f"# Filter: removed {n_dropped} Kaiser Q3 broadband (3-char station) rows\n")
        filtered.to_csv(f, index=False)

    print(f"\nWrote {len(filtered)} observations to {OUTPUT_CSV.name}")


if __name__ == "__main__":
    main()
